/**
 * Codex as the leader.
 *
 * Codex has the strongest restriction of the three and the weakest instruction
 * hook, so this adapter is shaped by that trade.
 *
 * - Restriction: `-c sandbox_mode="read-only" -c approval_policy="never"` is a
 *   kernel sandbox. It covers the shell, so there is no `sed -i` hole to patch
 *   and no hook to install. The neta MCP tools are pre-approved via
 *   `-c mcp_servers.neta.default_tools_approval_mode="approve"` so the leader is
 *   never interrupted for control-plane calls.
 * - MCP: `-c mcp_servers.neta.*` overrides, which is also why the control plane
 *   is reachable at all — the sandbox denies socket connections from the
 *   model's shell, but MCP servers run outside it.
 * - Instructions: Codex has no "append to system prompt" flag. It does read
 *   `$CODEX_HOME/AGENTS.md`, so Neta runs the session against an overlay home:
 *   every entry of the real home is symlinked in, and only AGENTS.md and
 *   hooks.json are replaced. Sessions, history and credentials still live in the
 *   real home through those links.
 *
 * That overlay used to live in the per-run temporary directory, and it caused a
 * real data loss: Codex records the absolute path of a session's rollout file in
 * its own thread index, so once the temporary directory was removed, `codex
 * resume <id>` could not find a transcript that was, in fact, safe in the real
 * Codex home. The overlay now lives at a stable Neta-owned path per logical
 * session, so the path Codex recorded still resolves months later.
 */

import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, lstatSync, readdirSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import {
	assertNoConversationSelectors,
	controlPlaneCommand,
	controlPlaneEnv,
	type LeaderAdapter,
	type LeaderLaunch,
	type LeaderLaunchContext,
	MCP_SERVER_NAME,
} from "./types.ts";

/** TOML basic string. Codex parses each `-c` value as TOML. */
function tomlString(value: string): string {
	return JSON.stringify(value);
}

/** Pass-through arguments that would move the leader to another conversation. */
export const CODEX_CONVERSATION_SELECTORS = ["resume", "fork", "--last", "--session", "--session-id", "--continue"];

export function configOverrides(context: LeaderLaunchContext): string[] {
	const { command, args } = controlPlaneCommand(context);
	const env = Object.entries(controlPlaneEnv(context))
		.map(([name, value]) => `${name} = ${tomlString(value)}`)
		.join(", ");
	return [
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.command=${tomlString(command)}`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.args=[${args.map(tomlString).join(", ")}]`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.env={ ${env} }`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.default_tools_approval_mode="approve"`,
		"-c",
		'sandbox_mode="read-only"',
		"-c",
		'approval_policy="never"',
	];
}

export function realCodexHome(env: NodeJS.ProcessEnv = process.env): string {
	return env.CODEX_HOME ?? join(homedir(), ".codex");
}

/** Generated by Neta on every run; everything else in the overlay is a symlink. */
const GENERATED_ENTRIES = ["AGENTS.md", "hooks.json"];

/**
 * Codex's SessionStart hook, the one supported way to learn the id Codex just
 * assigned. The payload arrives as JSON on stdin, with `session_id` and
 * `hook_event_name`, and `neta capture-leader-session` writes it into this
 * session's checkpoint.
 */
export function hooksConfig(realHome: string, capture: { command: string; args: string[] }): string {
	const existing = readJson(join(realHome, "hooks.json"));
	const hooks = isRecord(existing) && isRecord(existing.hooks) ? { ...existing.hooks } : {};
	const sessionStart = Array.isArray(hooks.SessionStart) ? [...hooks.SessionStart] : [];
	sessionStart.push({ hooks: [{ type: "command", command: [capture.command, ...capture.args].join(" ") }] });
	return `${JSON.stringify({ ...existing, hooks: { ...hooks, SessionStart: sessionStart } }, null, 2)}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readJson(path: string): Record<string, unknown> {
	try {
		const parsed: unknown = JSON.parse(readFileSync(path, "utf-8"));
		return isRecord(parsed) ? parsed : {};
	} catch {
		// No hooks of the user's own, or a file Codex would reject anyway.
		return {};
	}
}

/**
 * Build (or rebuild) the overlay home and return its path.
 *
 * Rebuilding is what makes resume safe: links to entries the real home no longer
 * has are dropped, new ones are added, and only the generated files are
 * rewritten — so a resumed session gets the current instructions without ever
 * copying credentials, history or sessions out of the real home.
 */
export async function createHomeOverlay(
	realHome: string,
	overlay: string,
	instructions: string,
	hooks?: string,
): Promise<string> {
	await mkdir(overlay, { recursive: true, mode: 0o700 });
	await chmod(overlay, 0o700);

	let existing = "";
	if (existsSync(realHome)) {
		const wanted = new Set(readdirSync(realHome).filter((entry) => !GENERATED_ENTRIES.includes(entry)));
		for (const entry of readdirSync(overlay)) {
			if (GENERATED_ENTRIES.includes(entry)) continue;
			const path = join(overlay, entry);
			// Only Neta's own links are pruned. Anything Codex turned into a real file
			// (a refreshed auth.json) is left for preserveRefreshedAuth to handle.
			try {
				if (!lstatSync(path).isSymbolicLink()) continue;
			} catch {
				continue;
			}
			if (!wanted.has(entry)) rmSync(path, { force: true });
		}
		for (const entry of wanted) {
			try {
				if (!existsSync(join(overlay, entry))) symlinkSync(join(realHome, entry), join(overlay, entry));
			} catch {
				// An entry we cannot link is one Codex will simply not see; that is
				// better than refusing to start the session.
			}
		}
		const agents = join(realHome, "AGENTS.md");
		if (existsSync(agents)) existing = `${readFileSync(agents, "utf-8").trim()}\n\n`;
	}

	await writeFile(join(overlay, "AGENTS.md"), `${existing}${instructions}\n`, { encoding: "utf-8", mode: 0o600 });
	if (hooks) await writeFile(join(overlay, "hooks.json"), hooks, { encoding: "utf-8", mode: 0o600 });
	else rmSync(join(overlay, "hooks.json"), { force: true });
	return overlay;
}

/**
 * Codex refreshes credentials by replacing auth.json, which turns our symlink
 * into a real file inside the overlay. Copy it back so the refresh is not lost
 * when the session ends.
 */
export function preserveRefreshedAuth(overlay: string, realHome: string): void {
	const overlayAuth = join(overlay, "auth.json");
	if (!existsSync(overlayAuth)) return;
	try {
		if (lstatSync(overlayAuth).isSymbolicLink()) return;
		copyFileSync(overlayAuth, join(realHome, "auth.json"));
	} catch {
		// Nothing to do: the user logs in again if it mattered.
	}
}

const hookSupport = new Map<string, boolean>();

/**
 * Whether the installed Codex has the hook mechanism at all.
 *
 * Hooks are how the exact conversation id is captured, and an older Codex
 * simply ignores an unknown `hooks.json`, which would leave Neta believing it
 * had arranged a capture that can never happen. Asking the installed binary is
 * cheap and is the only honest gate.
 */
export function codexSupportsHooks(binary: string, run: (path: string) => string = codexHelp): boolean {
	const cached = hookSupport.get(binary);
	if (cached !== undefined) return cached;
	const supported = /hook/i.test(run(binary));
	hookSupport.set(binary, supported);
	return supported;
}

function codexHelp(binary: string): string {
	try {
		return execFileSync(binary, ["--help"], {
			encoding: "utf-8",
			timeout: 10_000,
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (error) {
		const output = error as { stdout?: string };
		return typeof output.stdout === "string" ? output.stdout : "";
	}
}

export class CodexAdapter implements LeaderAdapter {
	readonly id = "codex" as const;

	// Verified against Codex: the same scheme Claude Code uses.
	toolName(base: string): string {
		return `mcp__${MCP_SERVER_NAME}__${base}`;
	}

	async prepare(context: LeaderLaunchContext): Promise<LeaderLaunch> {
		assertNoConversationSelectors(context.extraArgs, CODEX_CONVERSATION_SELECTORS, "Codex");
		const realHome = realCodexHome();
		// Falls back to the per-run directory only when no logical session owns
		// this launch, which is the plan-only path in tests.
		const overlay = join(context.leaderSessionDir ?? context.sessionDir, "codex-home");
		const warnings: string[] = [];
		const wanted = context.captureCommand && !context.resumeConversationId;
		if (wanted && !codexSupportsHooks(context.backend.path)) {
			throw new Error(
				"This Codex build has no session-start hook, which is how Neta records the exact conversation id, " +
					"so this session could never be reopened. Upgrade Codex to a build with hooks.",
			);
		}
		const capture = wanted ? context.captureCommand : undefined;
		await createHomeOverlay(
			realHome,
			overlay,
			context.leaderPrompt,
			capture ? hooksConfig(realHome, capture) : undefined,
		);

		// `codex resume <uuid>` is exact; `--last` and the picker are not, and Neta
		// never uses them. Config, MCP registration and instructions are rebuilt
		// from the installed binary on every run, including this one.
		const resume = context.resumeConversationId ? ["resume", context.resumeConversationId] : [];

		return {
			command: context.backend.path,
			args: [...resume, ...configOverrides(context), ...context.extraArgs],
			env: { ...controlPlaneEnv(context), CODEX_HOME: overlay },
			cleanup: async () => preserveRefreshedAuth(overlay, realHome),
			warnings,
		};
	}
}
