/**
 * Making Codex's session-start hook actually run.
 *
 * Codex 0.147 does not run a hook it has not been told to trust. A new or
 * changed hook is held back until someone reviews it in the TUI, or until the
 * invocation carries `--dangerously-bypass-hook-trust`, which un-reviews *every*
 * enabled hook — including project-local ones from a repository that was just
 * cloned. Neta uses neither: the hook that records the exact conversation id is
 * generated by Neta, so Neta vouches for that one hook and nothing else.
 *
 * The vouching is Codex's own mechanism, driven through Codex's own answers:
 *
 * 1. `codex app-server` + `hooks/list` reports every hook the session would
 *    run, each with the `key` Codex files trust under, the `currentHash` it
 *    computes, and whether it is trusted. No prompt, no model, no network.
 * 2. Neta writes `[hooks.state."<key>"] trusted_hash = "<currentHash>"` into the
 *    config the session will read — the persisted-trust record the TUI writes
 *    when a person clicks "Trust", for exactly the keys Neta vouches for.
 * 3. A second `hooks/list` confirms Codex now considers it trusted. If it does
 *    not, the launch fails: a session whose id can never be captured is a
 *    session that can never be reopened, and pretending otherwise is worse than
 *    refusing.
 *
 * That config is this session's own overlay copy, never the user's config.toml.
 * Writing trust into the shared file made two Neta launches race: each read it,
 * each appended its entry, and whichever wrote second dropped the other's, so a
 * session that had been confirmed as trusted started with an untrusted hook and
 * never reported its id. A copy per logical session has no such interleaving —
 * and leaves the user's own config exactly as they wrote it.
 *
 * Neta vouches for two kinds of hook, and no others: its own generated capture
 * hook, and a hook the user has already trusted in their own config — the overlay
 * home gives their hooks a new path, which Codex reads as a new hook, and
 * carrying the existing decision forward is not a new decision.
 */

import { spawn } from "node:child_process";
import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve, sep } from "node:path";

/** One hook as `hooks/list` reports it. Fields Neta does not use are ignored. */
export interface CodexHookEntry {
	key: string;
	eventName: string;
	command?: string | null;
	sourcePath: string;
	enabled: boolean;
	isManaged: boolean;
	currentHash: string;
	trustStatus: "managed" | "untrusted" | "trusted" | "modified";
}

export class CodexHookTrustError extends Error {}

/** How long the offline capability probe may take before it is treated as unavailable. */
const PROBE_TIMEOUT_MS = 20_000;

/**
 * Whether this Codex build withholds untrusted hooks.
 *
 * Builds before hook trust ran hooks as configured, and there is nothing to
 * arrange for them. The flag that bypasses trust is the build's own statement
 * that it enforces it.
 */
export function codexEnforcesHookTrust(help: string): boolean {
	return /--dangerously-bypass-hook-trust/.test(help);
}

/**
 * Ask the installed Codex what hooks this home would run.
 *
 * `codex app-server` is the local stdio service the Codex UIs are built on; this
 * uses the same `hooks/list` request its hook screen does. Nothing is prompted
 * and no provider is contacted.
 */
export async function probeCodexHooks(
	binary: string,
	codexHome: string,
	cwd: string,
	spawnProcess: typeof spawn = spawn,
): Promise<CodexHookEntry[]> {
	const child = spawnProcess(binary, ["app-server"], {
		cwd,
		env: { ...process.env, CODEX_HOME: codexHome },
		stdio: ["pipe", "pipe", "ignore"],
	});
	return new Promise<CodexHookEntry[]>((resolve, reject) => {
		let buffered = "";
		let settled = false;
		const finish = (outcome: () => void): void => {
			if (settled) return;
			settled = true;
			clearTimeout(timer);
			try {
				child.kill("SIGKILL");
			} catch {
				// Already gone; nothing to stop.
			}
			outcome();
		};
		const timer = setTimeout(
			() =>
				finish(() =>
					reject(new CodexHookTrustError(`\`${binary} app-server\` did not answer hooks/list within 20s`)),
				),
			PROBE_TIMEOUT_MS,
		);
		child.on("error", (error) => finish(() => reject(new CodexHookTrustError(error.message))));
		child.on("close", () =>
			finish(() => reject(new CodexHookTrustError(`\`${binary} app-server\` exited before answering hooks/list`))),
		);
		child.stdout?.on("data", (chunk: Buffer) => {
			buffered += chunk.toString();
			let index = buffered.indexOf("\n");
			while (index >= 0) {
				const line = buffered.slice(0, index);
				buffered = buffered.slice(index + 1);
				index = buffered.indexOf("\n");
				let message: { id?: unknown; result?: unknown; error?: { message?: unknown } };
				try {
					message = JSON.parse(line) as typeof message;
				} catch {
					continue;
				}
				if (message.id === 1) {
					send(child, { jsonrpc: "2.0", method: "initialized", params: {} });
					send(child, { jsonrpc: "2.0", id: 2, method: "hooks/list", params: { cwds: [cwd] } });
					continue;
				}
				if (message.id !== 2) continue;
				if (message.error) {
					const detail = typeof message.error.message === "string" ? message.error.message : "unknown error";
					finish(() => reject(new CodexHookTrustError(`hooks/list failed: ${detail}`)));
					return;
				}
				finish(() => resolve(readHookEntries(message.result)));
				return;
			}
		});
		send(child, {
			jsonrpc: "2.0",
			id: 1,
			method: "initialize",
			params: { clientInfo: { name: "neta", title: "neta", version: "0.0.0" } },
		});
	});
}

function send(child: ReturnType<typeof spawn>, message: unknown): void {
	try {
		child.stdin?.write(`${JSON.stringify(message)}\n`);
	} catch {
		// A closed pipe surfaces through the close handler.
	}
}

/** Every hook entry in a `hooks/list` response, whatever working directory reported it. */
export function readHookEntries(result: unknown): CodexHookEntry[] {
	const data = (result as { data?: unknown } | undefined)?.data;
	if (!Array.isArray(data)) return [];
	const entries: CodexHookEntry[] = [];
	for (const group of data) {
		const hooks = (group as { hooks?: unknown }).hooks;
		if (!Array.isArray(hooks)) continue;
		for (const hook of hooks) {
			const entry = hook as Partial<CodexHookEntry>;
			if (typeof entry.key !== "string" || typeof entry.currentHash !== "string") continue;
			if (typeof entry.sourcePath !== "string" || typeof entry.trustStatus !== "string") continue;
			entries.push({
				key: entry.key,
				eventName: typeof entry.eventName === "string" ? entry.eventName : "",
				command: typeof entry.command === "string" ? entry.command : undefined,
				sourcePath: entry.sourcePath,
				enabled: entry.enabled !== false,
				isManaged: entry.isManaged === true,
				currentHash: entry.currentHash,
				trustStatus: entry.trustStatus as CodexHookEntry["trustStatus"],
			});
		}
	}
	return entries;
}

/** Hashes this config already vouches for, whatever key they were trusted under. */
export function trustedHashes(config: string): Set<string> {
	return new Set([...config.matchAll(/^\s*trusted_hash\s*=\s*"([^"]+)"/gm)].map((match) => match[1]));
}

/**
 * Record trust for one hook key, leaving every other byte of the config alone.
 *
 * This file is the user's, so the edit is the smallest one that says what Codex
 * needs: an existing entry for this key has its hash updated in place, and a new
 * one is appended as its own table. A key that cannot be written as a TOML
 * basic string is refused rather than escaped into something Codex would
 * misparse — a corrupt config.toml would break Codex itself, not just Neta.
 */
export function upsertHookTrust(config: string, key: string, hash: string): string {
	if (/["\\\n]/.test(key) || /["\\\n]/.test(hash)) {
		throw new CodexHookTrustError(`Refusing to write a Codex hook trust entry for an unquotable key: ${key}`);
	}
	const header = `[hooks.state."${key}"]`;
	const index = config.indexOf(header);
	if (index === -1) {
		const separator = config === "" || config.endsWith("\n\n") ? "" : config.endsWith("\n") ? "\n" : "\n\n";
		return `${config}${separator}${header}\ntrusted_hash = "${hash}"\n`;
	}
	const start = index + header.length;
	const rest = config.slice(start);
	// The table ends at the next table header, which is the only place a later
	// key could belong to something else.
	const endMatch = /\n\s*\[/.exec(rest);
	const end = endMatch ? start + endMatch.index + 1 : config.length;
	const block = config.slice(start, end);
	const replaced = /^\s*trusted_hash\s*=\s*"[^"]*"\s*$/m.test(block)
		? block.replace(/^\s*trusted_hash\s*=\s*"[^"]*"\s*$/m, `trusted_hash = "${hash}"`)
		: `\ntrusted_hash = "${hash}"${block.startsWith("\n") ? block : `\n${block}`}`;
	return config.slice(0, start) + replaced + config.slice(end);
}

/**
 * Whether `path` is the directory `owner`, or something inside it.
 *
 * Comparing the two strings with `startsWith` is not the same question, and gets
 * the answer wrong in both directions: `~/.neta/leader-sessions-backup` is not
 * inside `~/.neta/leader-sessions`, and `~/.neta/leader-sessions/x/../../creds`
 * is not either, though both share the prefix. Both paths are resolved first —
 * which removes `.` and `..` — and the comparison then requires a separator, so
 * only a real path boundary counts. The names themselves are compared byte for
 * byte: a case-insensitive filesystem might resolve more paths into the
 * directory than this allows, and the cost of that is one dead entry left in a
 * file, against pruning something Neta does not own.
 */
export function pathIsInside(path: string, owner: string): boolean {
	const target = resolve(path);
	const root = resolve(owner);
	if (target === root) return true;
	return target.startsWith(root.endsWith(sep) ? root : root + sep);
}

/**
 * Drop trust entries for Neta-generated hook files that no longer exist.
 *
 * Each session's overlay home has its own path, so without this a config would
 * collect one dead entry per session forever. Only paths inside Neta's own
 * directory are ever removed, and only once the file they name is gone.
 */
export function pruneStaleNetaHookTrust(
	config: string,
	ownedPrefix: string,
	exists: (path: string) => boolean,
): string {
	let result = config;
	for (const match of [...config.matchAll(/^\[hooks\.state\."([^"]+)"]/gm)].reverse()) {
		const sourcePath = hookKeySourcePath(match[1]);
		if (!sourcePath || !pathIsInside(sourcePath, ownedPrefix) || exists(sourcePath)) continue;
		const start = result.indexOf(match[0]);
		if (start === -1) continue;
		const rest = result.slice(start + match[0].length);
		const endMatch = /\n\s*\[/.exec(rest);
		const end = endMatch ? start + match[0].length + endMatch.index + 1 : result.length;
		result = result.slice(0, start) + result.slice(end);
	}
	return result;
}

/**
 * The hook file a trust key names.
 *
 * A key is `<source path>:<event>:<group index>:<hook index>`, and the path
 * itself may contain colons — `C:\Users\...` on Windows, and any macOS or Linux
 * name may. So the three trailing fields are counted from the end, and a key
 * without them is not one Neta wrote and is left alone.
 */
export function hookKeySourcePath(key: string): string | undefined {
	const fields = key.split(":");
	if (fields.length < 4) return undefined;
	const path = fields.slice(0, -3).join(":");
	return path || undefined;
}

export interface CaptureHookTrustOptions {
	/** Codex binary to ask; the same one the session will run. */
	binary: string;
	/** The overlay home this session runs against, and whose own config.toml trust is written to. */
	codexHome: string;
	cwd: string;
	/** Absolute path of the generated hooks file Neta wrote. */
	hooksPath: string;
	/** The exact command line of Neta's capture hook, quoted as Codex will run it. */
	captureCommand: string;
	/** Test seam; production asks the installed binary. */
	probe?: (binary: string, codexHome: string, cwd: string) => Promise<CodexHookEntry[]>;
	/** Test seam for reading this session's config, between which and the write a race would live. */
	readConfig?: (path: string) => string;
	/** Test seam for writing this session's config. */
	writeConfig?: (path: string, contents: string) => void | Promise<void>;
}

/** What was arranged, for the launch report. */
export interface CaptureHookTrustResult {
	/** The trust key Codex files Neta's capture hook under. */
	key: string;
	/** Trust entries Neta wrote this launch, and the config file it wrote them to. */
	wrote: string[];
	configPath: string;
}

/**
 * Make sure this Codex will run Neta's capture hook, or fail the launch.
 *
 * Returns without writing anything when Codex already trusts the hook, which is
 * the normal case for the second and later runs of one session.
 */
export async function ensureCaptureHookTrusted(options: CaptureHookTrustOptions): Promise<CaptureHookTrustResult> {
	const probe = options.probe ?? probeCodexHooks;
	const readConfig = options.readConfig ?? readCodexConfigFile;
	const writeConfig = options.writeConfig ?? writeCodexConfigFile;

	const entries = await probe(options.binary, options.codexHome, options.cwd);
	const ours = entries.find(
		(entry) =>
			entry.sourcePath === options.hooksPath &&
			entry.eventName.toLowerCase() === "sessionstart" &&
			entry.command === options.captureCommand,
	);
	if (!ours) {
		throw new CodexHookTrustError(
			`This Codex did not report Neta's session-start capture hook from ${options.hooksPath}, so the exact ` +
				`conversation id could never be recorded and the session could never be reopened.`,
		);
	}
	if (!ours.enabled) {
		throw new CodexHookTrustError(
			`Codex reports Neta's session-start capture hook (${ours.key}) as disabled, so it would never record this ` +
				`session's conversation id. Re-enable hooks for this Codex home and start again.`,
		);
	}

	// This session's own config, generated from the user's when the overlay home
	// was built. Nothing else writes it, so the read below cannot go stale.
	const configPath = join(options.codexHome, "config.toml");
	// Already vouched for — the ordinary case for the second and later runs of one
	// session, and nothing to write or re-ask about.
	if (ours.trustStatus === "trusted" || ours.trustStatus === "managed") {
		return { key: ours.key, wrote: [], configPath };
	}
	const before = readConfig(configPath);
	// Trust Neta's own hook, plus the user's own hooks whose identical definition
	// their config already trusts under their real path. Nothing else.
	const alreadyTrusted = trustedHashes(before);
	const wanted = entries.filter(
		(entry) =>
			entry.sourcePath === options.hooksPath &&
			entry.trustStatus !== "trusted" &&
			entry.trustStatus !== "managed" &&
			(entry.key === ours.key || alreadyTrusted.has(entry.currentHash)),
	);
	const wrote: string[] = [];
	if (wanted.length > 0) {
		let config = before;
		for (const entry of wanted) {
			config = upsertHookTrust(config, entry.key, entry.currentHash);
			wrote.push(entry.key);
		}
		await writeConfig(configPath, config);
	}

	// Codex has the last word on whether it will run the hook. Ask it again
	// rather than assuming the write meant what we intended.
	const confirmed = (await probe(options.binary, options.codexHome, options.cwd)).find(
		(entry) => entry.key === ours.key,
	);
	if (!confirmed || (confirmed.trustStatus !== "trusted" && confirmed.trustStatus !== "managed")) {
		throw new CodexHookTrustError(
			`Codex still does not trust Neta's session-start capture hook (${ours.key}) after recording trust in ` +
				`${configPath}, so it would never report this session's conversation id.`,
		);
	}
	return { key: ours.key, wrote, configPath };
}

/**
 * A Codex config file's contents, or "" when there is no such file.
 *
 * Only "no such file" reads as empty. Anything else — a directory in its place,
 * a file the process may not read, an I/O error — is raised, because both callers
 * write a config derived from what this returns: treating an unreadable file as
 * empty would generate a session config with none of the user's settings in it,
 * and (before the overlay copy existed) could have written that back over
 * theirs. Refusing the launch is the only honest answer.
 */
export function readCodexConfigFile(path: string): string {
	try {
		return readFileSync(path, "utf-8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") return "";
		const detail = error instanceof Error ? error.message : String(error);
		throw new CodexHookTrustError(
			`could not read the Codex config at ${path}: ${detail}. Neta will not guess at its contents, so nothing was started.`,
		);
	}
}

/** Atomic, so a config Codex is reading is never half a file. */
export function writeCodexConfigFile(path: string, contents: string): void {
	mkdirSync(dirname(path), { recursive: true });
	const temp = `${path}.neta-${process.pid}.tmp`;
	try {
		writeFileSync(temp, contents, { encoding: "utf-8", mode: 0o600 });
		renameSync(temp, path);
	} catch (error) {
		// A Codex config can hold API keys, so a failed write leaves no half-copy of
		// one lying beside it.
		rmSync(temp, { force: true });
		throw error;
	}
}
