/**
 * Codex as the leader.
 *
 * Codex has the strongest restriction of the three and the weakest instruction
 * hook, so this adapter is shaped by that trade.
 *
 * - Restriction: `-c sandbox_mode="read-only" -c approval_policy="never"` is a
 *   kernel sandbox. It covers the shell, so there is no `sed -i` hole to patch
 *   and no hook to install. The neta MCP tools are pre-approved via
 *   `-c mcp_servers.neta.default_tools_approval_mode="approve"` so the leader is
 *   never interrupted for control-plane calls.
 * - MCP: `-c mcp_servers.neta.*` overrides, which is also why the control plane
 *   is reachable at all — the sandbox denies socket connections from the
 *   model's shell, but MCP servers run outside it.
 * - Instructions: Codex has no "append to system prompt" flag. It does read
 *   `$CODEX_HOME/AGENTS.md`, so Neta runs the session against an overlay home:
 *   every entry of the real home is symlinked in, and only AGENTS.md, hooks.json
 *   and config.toml are replaced. Sessions, history and credentials still live in
 *   the real home through those links.
 *
 * That overlay used to live in the per-run temporary directory, and it caused a
 * real data loss: Codex records the absolute path of a session's rollout file in
 * its own thread index, so once the temporary directory was removed, `codex
 * resume <id>` could not find a transcript that was, in fact, safe in the real
 * Codex home. The overlay now lives at a stable Neta-owned path per logical
 * session, so the path Codex recorded still resolves months later.
 *
 * config.toml is generated rather than linked for one reason: hook trust. Codex
 * files a hook's trust in the config the session reads, and Neta has to record
 * trust for its own capture hook before the session starts. Writing that into the
 * user's shared config.toml made two Neta launches in two directories race each
 * other — each read the file, each appended its own entry, and the second write
 * dropped the first, leaving one session whose capture hook Codex would never run
 * and whose id could therefore never be recorded. Each session now gets its own
 * copy of the user's config, generated from their current one, with trust added
 * only inside that copy. The user's config.toml is read and never written.
 */

import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
	chmodSync,
	closeSync,
	existsSync,
	fsyncSync,
	lstatSync,
	openSync,
	readdirSync,
	readFileSync,
	realpathSync,
	renameSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { shellQuote } from "../cli-shim.ts";
import { APP_NAME } from "../config.ts";
import {
	codexEnforcesHookTrust,
	ensureCaptureHookTrusted,
	pruneStaleNetaHookTrust,
	readCodexConfigFile,
} from "./codex-hooks.ts";
import {
	assertNoConversationSelectors,
	controlPlaneCommand,
	controlPlaneEnv,
	type LeaderAdapter,
	type LeaderLaunch,
	type LeaderLaunchContext,
	MCP_SERVER_NAME,
} from "./types.ts";

/** TOML basic string. Codex parses each `-c` value as TOML. */
function tomlString(value: string): string {
	return JSON.stringify(value);
}

/** Pass-through arguments that would move the leader to another conversation. */
export const CODEX_CONVERSATION_SELECTORS = ["resume", "fork", "--last", "--session", "--session-id", "--continue"];

export function configOverrides(context: LeaderLaunchContext): string[] {
	const { command, args } = controlPlaneCommand(context);
	const env = Object.entries(controlPlaneEnv(context))
		.map(([name, value]) => `${name} = ${tomlString(value)}`)
		.join(", ");
	return [
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.command=${tomlString(command)}`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.args=[${args.map(tomlString).join(", ")}]`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.env={ ${env} }`,
		"-c",
		`mcp_servers.${MCP_SERVER_NAME}.default_tools_approval_mode="approve"`,
		"-c",
		'sandbox_mode="read-only"',
		"-c",
		'approval_policy="never"',
	];
}

export function realCodexHome(env: NodeJS.ProcessEnv = process.env): string {
	return env.CODEX_HOME ?? join(homedir(), ".codex");
}

/** Generated by Neta on every run; everything else in the overlay is a symlink. */
const GENERATED_ENTRIES = ["AGENTS.md", "hooks.json", "config.toml"];

/**
 * Codex 0.147 runs a hook from one command *string* — there is no argv form, only
 * `command` and its Windows counterpart `commandWindows` — so the string is
 * quoted rather than joined with spaces.
 *
 * The arguments are not Neta's to sanitise: the executable is wherever the user
 * installed `neta` (`~/Library/Application Support/…`, a checkout under a
 * directory with an apostrophe in it), and the Neta directory comes from
 * `NETA_DIR`. Joining those with spaces turns a path with a space into two
 * arguments and a path with a `;` or a backtick into a second command. Inside
 * POSIX single quotes every byte is literal, and the only character needing
 * treatment is the quote itself: close, escape, reopen.
 */
export function posixHookCommand(argv: string[]): string {
	return argv.map(shellQuote).join(" ");
}

/**
 * The same command for a Windows Codex, which runs it through `cmd.exe`.
 *
 * Double quotes make the shell metacharacters literal and `CommandLineToArgvW`
 * splits the result back into the arguments Neta meant — except for a handful of
 * characters `cmd.exe` expands *inside* quotes (`%VAR%`, delayed `!VAR!`) or
 * cannot carry at all. Those are reported as unrepresentable rather than
 * mis-quoted: `undefined` here becomes a refused launch on Windows and a
 * POSIX-only hook everywhere else.
 */
export function windowsHookCommand(argv: string[]): string | undefined {
	if (argv.some(cmdUnrepresentable)) return undefined;
	return (
		argv
			// A trailing backslash would otherwise escape the closing quote.
			.map((argument) => `"${argument.replace(/(\\+)$/, "$1$1")}"`)
			.join(" ")
	);
}

/** `%` and `!` are expanded inside double quotes; `"` ends them; control characters end the line. */
function cmdUnrepresentable(argument: string): boolean {
	return /["%!]/.test(argument) || [...argument].some((character) => character.charCodeAt(0) < 0x20);
}

/** The exact string Codex will run for this platform, and report back as the hook's command. */
export function captureHookCommand(
	capture: { command: string; args: string[] },
	platform: NodeJS.Platform = process.platform,
): string {
	const argv = [capture.command, ...capture.args];
	if (platform !== "win32") return posixHookCommand(argv);
	const windows = windowsHookCommand(argv);
	if (!windows) throw new Error(unrepresentableOnWindows(argv));
	return windows;
}

function unrepresentableOnWindows(argv: string[]): string {
	return (
		`Neta's session-start capture hook cannot be expressed as a cmd.exe command line: ` +
		`${argv.find((argument) => /["%!\r\n]/.test(argument))} contains a character cmd.exe would expand or drop. ` +
		`Move Neta or its directory (NETA_DIR) somewhere without ", %, ! or a line break in the path.`
	);
}

/**
 * Codex's SessionStart hook, the one supported way to learn the id Codex just
 * assigned. The payload arrives as JSON on stdin, with `session_id` and
 * `hook_event_name`, and `neta capture-leader-session` writes it into this
 * session's checkpoint.
 */
export function hooksConfig(
	realHome: string,
	capture: { command: string; args: string[] },
	warn: (message: string) => void = () => {},
	platform: NodeJS.Platform = process.platform,
): string {
	const existing = readUserHooks(join(realHome, "hooks.json"), warn);
	const hooks = isRecord(existing.hooks) ? { ...existing.hooks } : {};
	const sessionStart = Array.isArray(hooks.SessionStart) ? [...hooks.SessionStart] : [];
	const argv = [capture.command, ...capture.args];
	const windows = windowsHookCommand(argv);
	if (platform === "win32" && !windows) throw new Error(unrepresentableOnWindows(argv));
	sessionStart.push({
		hooks: [{ type: "command", command: posixHookCommand(argv), ...(windows ? { commandWindows: windows } : {}) }],
	});
	return `${JSON.stringify({ ...existing, hooks: { ...hooks, SessionStart: sessionStart } }, null, 2)}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * The user's own hooks, which the generated file has to carry forward.
 *
 * A file that is there but unreadable is refused: generating an overlay
 * hooks.json from nothing would silently drop every hook the user runs Codex
 * with. A file that is there but not JSON is one Codex would reject anyway, so
 * the session goes ahead with Neta's hook alone — and says so.
 */
function readUserHooks(path: string, warn: (message: string) => void): Record<string, unknown> {
	let raw: string;
	try {
		raw = readFileSync(path, "utf-8");
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") return {};
		throw new Error(
			`could not read your Codex hooks at ${path}: ${describeError(error)}. Starting without them would silently ` +
				`drop hooks you rely on, so nothing was started.`,
		);
	}
	try {
		const parsed: unknown = JSON.parse(raw);
		if (isRecord(parsed)) return parsed;
	} catch {
		// Reported below rather than swallowed.
	}
	warn(`your Codex hooks at ${path} are not a JSON object, so this session runs only Neta's own capture hook`);
	return {};
}

/**
 * Build (or rebuild) the overlay home and return its path.
 *
 * Rebuilding is what makes resume safe: links to entries the real home no longer
 * has are dropped, new ones are added, and only the generated files are
 * rewritten — so a resumed session gets the current instructions without ever
 * copying credentials, history or sessions out of the real home.
 *
 * config.toml is the one entry copied rather than linked, so that this session's
 * hook trust has somewhere private to live. It is regenerated from the user's
 * current config on every run, including a resume, which is also what stops
 * Neta's own dead trust entries from accumulating in the copy.
 */
export async function createHomeOverlay(
	realHome: string,
	overlay: string,
	instructions: string,
	hooks?: string,
	/** Neta's directory of generated Codex homes; dead trust entries under it are dropped from the copy. */
	ownedPrefix?: string,
): Promise<string> {
	await mkdir(overlay, { recursive: true, mode: 0o700 });
	await chmod(overlay, 0o700);

	// Read before anything is written: an unreadable config must stop the launch,
	// not produce an overlay that silently runs Codex with none of the user's
	// settings.
	const userConfig = readCodexConfigFile(join(realHome, "config.toml"));

	let existing = "";
	if (existsSync(realHome)) {
		const wanted = new Set(readdirSync(realHome).filter((entry) => !GENERATED_ENTRIES.includes(entry)));
		for (const entry of readdirSync(overlay)) {
			if (GENERATED_ENTRIES.includes(entry)) continue;
			const path = join(overlay, entry);
			// Only Neta's own links are pruned. Anything Codex turned into a real file
			// (a refreshed auth.json) is left for preserveRefreshedAuth to handle.
			try {
				if (!lstatSync(path).isSymbolicLink()) continue;
			} catch {
				continue;
			}
			if (!wanted.has(entry)) rmSync(path, { force: true });
		}
		for (const entry of wanted) {
			try {
				if (!existsSync(join(overlay, entry))) symlinkSync(join(realHome, entry), join(overlay, entry));
			} catch {
				// An entry we cannot link is one Codex will simply not see; that is
				// better than refusing to start the session.
			}
		}
		const agents = join(realHome, "AGENTS.md");
		if (existsSync(agents)) existing = `${readFileSync(agents, "utf-8").trim()}\n\n`;
	}

	await writeFile(join(overlay, "AGENTS.md"), `${existing}${instructions}\n`, { encoding: "utf-8", mode: 0o600 });
	if (hooks) await writeFile(join(overlay, "hooks.json"), hooks, { encoding: "utf-8", mode: 0o600 });
	else rmSync(join(overlay, "hooks.json"), { force: true });
	// The copy may carry the user's API keys, so it is theirs to read and nobody
	// else's — same mode the real one gets from Codex.
	await writeFile(
		join(overlay, "config.toml"),
		ownedPrefix ? pruneStaleNetaHookTrust(userConfig, ownedPrefix, existsSync) : userConfig,
		{ encoding: "utf-8", mode: 0o600 },
	);
	return overlay;
}

/**
 * Codex refreshes credentials by replacing auth.json, which turns our symlink
 * into a real file inside the overlay.
 *
 * Copy the refreshed credentials back to the real home, then put the symlink
 * back — so the one copy of the user's Codex credentials stays in the user's
 * own Codex home and Neta's session directory retains none. The order matters:
 * the overlay copy is only removed after the real home is confirmed to hold the
 * same bytes, so a failure anywhere leaves the credentials where they are and
 * says so out loud rather than deleting the only good copy.
 *
 * The copy goes through a temporary file beside the real one, which makes the
 * replacement atomic and makes a half-written credential file impossible — but
 * that temporary file holds the user's credentials too. Every failure path
 * removes it, and a removal that itself fails is named in the report rather than
 * left for the user to discover.
 */
export function preserveRefreshedAuth(
	overlay: string,
	realHome: string,
	report: (message: string) => void = (message) => process.stderr.write(`${APP_NAME}: ${message}\n`),
	/** Test seam: production uses node:fs. Each stage can be made to fail on its own. */
	ops: Partial<AuthFileOps> = {},
): void {
	const fs = { ...realAuthFileOps, ...ops };
	const overlayAuth = join(overlay, "auth.json");
	const realAuth = join(realHome, "auth.json");
	if (!existsSync(overlayAuth)) return;
	try {
		if (lstatSync(overlayAuth).isSymbolicLink()) return;
	} catch {
		return;
	}
	let refreshed: Buffer;
	try {
		refreshed = readFileSync(overlayAuth);
	} catch (error) {
		// Nothing can be moved, and the file is still sitting in Neta's directory
		// with the user's credentials in it. Say so rather than exiting quietly.
		report(
			`could not read Codex's refreshed credentials at ${overlayAuth}: ${describeError(error)}. That file holds ` +
				`your Codex credentials; move it into ${realHome} yourself, or delete it and log in to Codex again.`,
		);
		return;
	}
	// Same directory as the destination, so the rename is atomic and a torn
	// write can never be what the user's next Codex login reads.
	const temp = `${realAuth}.neta-${process.pid}-${randomBytes(6).toString("hex")}.tmp`;
	try {
		const handle = fs.open(temp, "wx", 0o600);
		try {
			fs.write(handle, refreshed);
			fs.fsync(handle);
		} finally {
			try {
				fs.close(handle);
			} catch {
				// The bytes are already on disk; a descriptor that will not close is
				// not a reason to abandon a good copy.
			}
		}
		fs.rename(temp, realAuth);
	} catch (error) {
		const stuck = removeTempAuth(temp, fs);
		report(
			`could not copy Codex's refreshed credentials back to ${realAuth}: ${describeError(error)}. ` +
				`They are still in ${overlayAuth}; move that file yourself, or log in to Codex again.` +
				(stuck
					? ` Neta could not remove its temporary copy at ${temp}: ${stuck}. Delete that file yourself — it holds ` +
						`your Codex credentials.`
					: ""),
		);
		return;
	}
	try {
		fs.chmod(realAuth, 0o600);
	} catch (error) {
		// The file was created 0600 and a umask can only take bits away, so this is
		// hardening rather than the thing that makes it private. Say so and go on.
		report(
			`could not set the permissions on ${realAuth}: ${describeError(error)}. Codex's credentials were written ` +
				`there; check that file is readable only by you.`,
		);
	}
	// Only now is deleting safe: the real home holds these exact bytes.
	try {
		if (!readFileSync(realAuth).equals(refreshed)) {
			report(
				`Codex's credentials in ${realAuth} are not the ones this session refreshed; ` +
					`leaving Neta's copy at ${overlayAuth} rather than deleting it.`,
			);
			return;
		}
		rmSync(overlayAuth, { force: true });
		symlinkSync(realAuth, overlayAuth);
	} catch (error) {
		report(
			`could not restore the credentials symlink in ${overlay}: ${describeError(error)}. ` +
				`Remove ${overlayAuth} yourself: it is a copy of your Codex credentials.`,
		);
	}
}

/** The file operations the credential move goes through, one per failure mode a test can inject. */
export interface AuthFileOps {
	open: (path: string, flags: string, mode: number) => number;
	write: (handle: number, data: Buffer) => void;
	fsync: (handle: number) => void;
	close: (handle: number) => void;
	rename: (from: string, to: string) => void;
	chmod: (path: string, mode: number) => void;
	remove: (path: string) => void;
}

const realAuthFileOps: AuthFileOps = {
	open: openSync,
	write: writeFileSync,
	fsync: fsyncSync,
	close: closeSync,
	rename: renameSync,
	chmod: chmodSync,
	remove: (path) => rmSync(path, { force: true }),
};

/** Returns what went wrong, or undefined when nothing of the temporary file is left. */
function removeTempAuth(temp: string, fs: AuthFileOps): string | undefined {
	try {
		fs.remove(temp);
	} catch (error) {
		// `force` already ignores a file that was never created; anything reaching
		// here is a file that exists and would not go.
		return describeError(error);
	}
	return existsSync(temp) ? "it is still there" : undefined;
}

function describeError(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

const helpText = new Map<string, string>();

function cachedHelp(binary: string, run: (path: string) => string): string {
	const cached = helpText.get(binary);
	if (cached !== undefined) return cached;
	const help = run(binary);
	helpText.set(binary, help);
	return help;
}

/**
 * Whether the installed Codex has the hook mechanism at all.
 *
 * Hooks are how the exact conversation id is captured, and an older Codex
 * simply ignores an unknown `hooks.json`, which would leave Neta believing it
 * had arranged a capture that can never happen. Asking the installed binary is
 * cheap and is the only honest gate.
 */
export function codexSupportsHooks(binary: string, run: (path: string) => string = codexHelp): boolean {
	return /hook/i.test(cachedHelp(binary, run));
}

/** Whether this build withholds hooks it has not been told to trust. */
export function codexRequiresHookTrust(binary: string, run: (path: string) => string = codexHelp): boolean {
	return codexEnforcesHookTrust(cachedHelp(binary, run));
}

function codexHelp(binary: string): string {
	try {
		return execFileSync(binary, ["--help"], {
			encoding: "utf-8",
			timeout: 10_000,
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (error) {
		const output = error as { stdout?: string };
		return typeof output.stdout === "string" ? output.stdout : "";
	}
}

export class CodexAdapter implements LeaderAdapter {
	readonly id = "codex" as const;

	// Verified against Codex: the same scheme Claude Code uses.
	toolName(base: string): string {
		return `mcp__${MCP_SERVER_NAME}__${base}`;
	}

	async prepare(context: LeaderLaunchContext): Promise<LeaderLaunch> {
		assertNoConversationSelectors(context.extraArgs, CODEX_CONVERSATION_SELECTORS, "Codex");
		const realHome = realCodexHome();
		// Falls back to the per-run directory only when no logical session owns
		// this launch, which is the plan-only path in tests.
		const overlay = join(context.leaderSessionDir ?? context.sessionDir, "codex-home");
		const warnings: string[] = [];
		const wanted = context.captureCommand && !context.resumeConversationId;
		if (wanted && !codexSupportsHooks(context.backend.path)) {
			throw new Error(
				"This Codex build has no session-start hook, which is how Neta records the exact conversation id, " +
					"so this session could never be reopened. Upgrade Codex to a build with hooks.",
			);
		}
		const capture = wanted ? context.captureCommand : undefined;
		// Every generated Codex home lives under this one directory, which is what
		// makes dropping dead trust entries a Neta-only operation.
		const ownedPrefix = context.leaderSessionDir ? dirname(context.leaderSessionDir) : overlay;
		await createHomeOverlay(
			realHome,
			overlay,
			context.leaderPrompt,
			capture ? hooksConfig(realHome, capture, (message) => warnings.push(message)) : undefined,
			ownedPrefix,
		);

		// The hook file exists now, so Codex can be asked about it by name. A build
		// that enforces hook trust runs nothing it has not been told to trust, and
		// an unrunnable capture hook means an unreopenable session — so this either
		// arranges trust for Neta's own hook or refuses the launch.
		if (capture && codexRequiresHookTrust(context.backend.path)) {
			const trusted = await ensureCaptureHookTrusted({
				binary: context.backend.path,
				codexHome: overlay,
				cwd: context.cwd,
				hooksPath: realpathSync(join(overlay, "hooks.json")),
				captureCommand: captureHookCommand(capture),
			});
			if (trusted.wrote.length > 0) {
				warnings.push(
					`recorded Codex hook trust for ${trusted.wrote.length} hook${trusted.wrote.length === 1 ? "" : "s"} ` +
						`in this session's own ${trusted.configPath}; your Codex config was not changed`,
				);
			}
		}

		// `codex resume <uuid>` is exact; `--last` and the picker are not, and Neta
		// never uses them. Config, MCP registration and instructions are rebuilt
		// from the installed binary on every run, including this one.
		const resume = context.resumeConversationId ? ["resume", context.resumeConversationId] : [];

		return {
			command: context.backend.path,
			args: [...resume, ...configOverrides(context), ...context.extraArgs],
			env: { ...controlPlaneEnv(context), CODEX_HOME: overlay },
			cleanup: async () => preserveRefreshedAuth(overlay, realHome),
			warnings,
		};
	}
}
