/**
 * OpenCode as the leader.
 *
 * OpenCode takes everything from one config object, which Neta passes inline
 * through `OPENCODE_CONFIG_CONTENT` so nothing is written into the user's
 * config directory:
 *
 * - `instructions` points at a file holding the leader instructions.
 * - `mcp.neta` registers the control plane as a local server.
 * - `permission.edit: "deny"` removes the edit tools.
 * - `plugin` loads one generated file whose only job is to report the session
 *   id OpenCode assigns, so the session can be reopened exactly.
 *
 * OpenCode's permission config accepts ordered glob rules for bash commands.
 * Start from deny and allow only read-only inspection commands. This remains
 * weaker than Codex's kernel sandbox, but avoids a denylist that silently lets
 * a newly-shaped write command through.
 *
 * Sessions stay in OpenCode's own global storage. Neta adds config and one
 * plugin file at a stable path of its own; it never relocates OpenCode's data
 * directory, so nothing it writes can strand a session behind a deleted path.
 */

import { execFileSync } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { vendorSessionCaptureErrorPath, vendorSessionCapturePath } from "../checkpoint.ts";
import {
	assertNoConversationSelectors,
	controlPlaneCommand,
	controlPlaneEnv,
	type LeaderAdapter,
	type LeaderLaunch,
	type LeaderLaunchContext,
	MCP_SERVER_NAME,
} from "./types.ts";

/** Explicit inspection commands allowed after the catch-all deny rule. */
export const READ_ONLY_BASH_PATTERNS = [
	"ls",
	"ls *",
	"cat",
	"cat *",
	"grep",
	"grep *",
	"rg",
	"rg *",
	"find",
	"find *",
	"head",
	"head *",
	"tail",
	"tail *",
	"wc",
	"wc *",
	"pwd",
	"which *",
	"type *",
	"stat *",
	"file *",
	"du *",
	"df",
	"df *",
	"git status",
	"git status *",
	"git log",
	"git log *",
	"git diff",
	"git diff *",
	"git show",
	"git show *",
	"git branch",
	"git branch *",
	"git rev-parse *",
	"git ls-files",
	"git ls-files *",
	"git grep *",
	"git blame *",
	"git show-ref",
	"git show-ref *",
	"git worktree list",
];

/** Pass-through arguments that would move the leader to another conversation. */
export const OPENCODE_CONVERSATION_SELECTORS = ["-c", "--continue", "-s", "--session", "--fork"];

/** `--pure` runs OpenCode without external plugins, which is where the capture lives. */
const PURE_FLAG = "--pure";

export function openCodeConfig(
	context: LeaderLaunchContext,
	instructionsPath: string,
	capturePluginPath?: string,
): string {
	const { command, args } = controlPlaneCommand(context);
	const bash: Record<string, "allow" | "deny"> = { "*": "deny" };
	for (const pattern of READ_ONLY_BASH_PATTERNS) bash[pattern] = "allow";

	return JSON.stringify(
		{
			$schema: "https://opencode.ai/config.json",
			instructions: [instructionsPath],
			permission: { edit: "deny", bash },
			...(capturePluginPath ? { plugin: [pathToFileURL(capturePluginPath).href] } : {}),
			mcp: {
				[MCP_SERVER_NAME]: {
					type: "local",
					command: [command, ...args],
					enabled: true,
					environment: controlPlaneEnv(context),
				},
			},
		},
		null,
		2,
	);
}

/**
 * The plugin that reports the id OpenCode assigned.
 *
 * OpenCode generates its own session ids (`ses_…`) and offers no way to name
 * one, so the exact id has to be observed rather than chosen. The leader runs
 * in OpenCode's own TUI rather than over ACP, so there is no `session/new`
 * response to read it from; what there is, is the plugin `event` hook, which
 * receives every bus event with the whole `Session` object attached.
 *
 * Every filter here exists to make that observation exact rather than a
 * "most recent session" lookup, which would be a race with anything else the
 * user is running:
 *
 * - the plugin instance belongs to this leader's own OpenCode process;
 * - `session.created` is the creation event itself, not a listing;
 * - a session with a `parentID` is a subagent's, not the leader's;
 * - a session whose project directory is unrelated to this launch is not ours;
 * - and a `session.updated` is only accepted for a session created after this
 *   launch began, so an older session being touched can never be mistaken for
 *   the new one.
 *
 * Deliberately tiny and defensive: a plugin that throws is a broken editor
 * session, and a session that fails to record its id is merely one `neta
 * resume` will refuse.
 */
export function capturePluginSource(
	capture: { path: string; errorPath: string },
	directory: string,
	launchedAt: number = Date.now(),
): string {
	return `// Generated by Neta. Records the session id OpenCode assigns, once, so the
// session can be reopened later with \`opencode --session <id>\`.
import { closeSync, fsyncSync, openSync, realpathSync, renameSync, writeFileSync, writeSync } from "node:fs";

const CAPTURE = ${JSON.stringify(capture)};
const DIRECTORY = ${JSON.stringify(directory)};
const LAUNCHED_AT = ${JSON.stringify(launchedAt)};
let reported = false;

function resolve(path) {
	try {
		return realpathSync(path);
	} catch {
		return path;
	}
}

/**
 * OpenCode reports a session's project directory, which is the worktree root
 * and may be an ancestor of the directory Neta was started in — and on macOS it
 * comes back resolved (\`/private/tmp\`) where ours is not. Compare resolved
 * paths, and treat an ancestor as this leader's own.
 */
function belongsHere(directory) {
	if (!directory) return true;
	const session = resolve(directory);
	const leader = resolve(DIRECTORY);
	return leader === session || leader.startsWith(session.endsWith("/") ? session : session + "/");
}

/**
 * Written here rather than handed to a subprocess: one atomic rename, no
 * spawn to lose the error in. A failure is recorded beside it so the control
 * plane can say the session is not resumable instead of everyone assuming it is.
 */
function report(session) {
	if (reported) return;
	reported = true;
	const temp = CAPTURE.path + "." + process.pid + ".tmp";
	try {
		const handle = openSync(temp, "wx", 0o600);
		try {
			writeSync(handle, JSON.stringify({ vendorConversationId: session.id, at: Date.now() }) + "\\n");
			fsyncSync(handle);
		} finally {
			closeSync(handle);
		}
		renameSync(temp, CAPTURE.path);
	} catch (error) {
		reported = false;
		try {
			writeFileSync(CAPTURE.errorPath, "could not record session " + session.id + ": " + String(error) + "\\n", {
				mode: 0o600,
			});
		} catch {
			// Nothing left to write to; the control plane still reports the missing id.
		}
	}
}

export default async () => ({
	event: async ({ event }) => {
		const created = event?.type === "session.created";
		if (!created && event?.type !== "session.updated") return;
		const session = event.properties?.info;
		// A child session belongs to a subagent, and one from an unrelated
		// directory is not this leader's: either would record the wrong id.
		if (!session?.id || session.parentID) return;
		if (!belongsHere(session.directory)) return;
		// An update is only this launch's session if the session itself was
		// created by this launch. Without that check, OpenCode touching an older
		// session would look exactly like the new one.
		if (!created && !(typeof session.time?.created === "number" && session.time.created >= LAUNCHED_AT)) return;
		report(session);
	},
});
`;
}

const pluginSupport = new Map<string, boolean>();

/**
 * Whether the installed OpenCode has plugins at all. Without them there is no
 * supported way to learn the session id, and Neta says so instead of pretending
 * the session is resumable.
 */
export function openCodeSupportsPlugins(binary: string, run: (path: string) => string = openCodeHelp): boolean {
	const cached = pluginSupport.get(binary);
	if (cached !== undefined) return cached;
	const supported = /plugin/i.test(run(binary));
	pluginSupport.set(binary, supported);
	return supported;
}

function openCodeHelp(binary: string): string {
	try {
		return execFileSync(binary, ["--help"], {
			encoding: "utf-8",
			timeout: 10_000,
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (error) {
		const output = error as { stdout?: string };
		return typeof output.stdout === "string" ? output.stdout : "";
	}
}

export class OpenCodeAdapter implements LeaderAdapter {
	readonly id = "opencode" as const;

	// Verified against OpenCode, which joins with one underscore and no prefix.
	toolName(base: string): string {
		return `${MCP_SERVER_NAME}_${base}`;
	}

	async prepare(context: LeaderLaunchContext): Promise<LeaderLaunch> {
		assertNoConversationSelectors(context.extraArgs, OPENCODE_CONVERSATION_SELECTORS, "OpenCode");
		const instructionsPath = join(context.sessionDir, "leader.md");
		await writeFile(instructionsPath, `${context.leaderPrompt}\n`, "utf-8");

		const warnings = [
			"OpenCode has no kernel sandbox: bash is denied by default and only read-only inspection commands are allowed, which is weaker than Codex's read-only sandbox.",
		];
		// Only a fresh session needs capturing; a resumed one already knows which
		// conversation it is in.
		const wanted = context.captureCommand && !context.resumeConversationId;
		if (wanted && context.extraArgs.includes(PURE_FLAG)) {
			throw new Error(
				`\`${PURE_FLAG}\` runs OpenCode without plugins, which is how Neta records the exact conversation id, ` +
					"so this session could never be reopened. Drop it, or start the session without Neta.",
			);
		}
		if (wanted && !openCodeSupportsPlugins(context.backend.path)) {
			throw new Error(
				"This OpenCode build has no plugin support, which is how Neta records the exact conversation id, " +
					"so this session could never be reopened. Upgrade OpenCode to a build with plugins.",
			);
		}

		let capturePluginPath: string | undefined;
		if (wanted) {
			const captureDir = context.leaderSessionDir ?? context.sessionDir;
			// Beside the session's other generated state, not in the per-run
			// temporary directory, so a resumed session regenerates it in place.
			capturePluginPath = join(captureDir, "opencode-session-capture.mjs");
			await writeFile(
				capturePluginPath,
				capturePluginSource(
					{ path: vendorSessionCapturePath(captureDir), errorPath: vendorSessionCaptureErrorPath(captureDir) },
					context.cwd,
				),
				{ encoding: "utf-8", mode: 0o600 },
			);
		}

		// `--session <id>` is OpenCode's exact resume. `--continue` and `--fork`
		// are the inexact ones, and Neta uses neither.
		const resume = context.resumeConversationId ? ["--session", context.resumeConversationId] : [];

		return {
			command: context.backend.path,
			args: [...resume, ...context.extraArgs],
			env: {
				...controlPlaneEnv(context),
				OPENCODE_CONFIG_CONTENT: openCodeConfig(context, instructionsPath, capturePluginPath),
			},
			warnings,
		};
	}
}
