import { createHash } from "node:crypto";

// Agent display names. The first 117 come from the NoScrubs dataset
// (`design/canvas-directions/dataset.json`: mission agent names, mission lead
// names, then mission `leadName`s, first-seen order); the rest extend the pool
// to 200 in the same short word-name register.
//
// The plan asks that no two names share a three-letter prefix. Four pairs
// inherited from the dataset break that rule — Yara/Yarrow, Maren/Marlowe,
// June/Juniper, Tam/Tamsin — and are kept verbatim anyway: dropping dataset
// names would break the pool's other contract. Every added name avoids all
// used prefixes, and the test pins the four exceptions.
export const NAME_POOL: readonly string[] = [
	"Lark",
	"Cleo",
	"Rafe",
	"Kai",
	"Xen",
	"Hattie",
	"Poe",
	"Zane",
	"Gwen",
	"Lena",
	"Piet",
	"Uri",
	"Vern",
	"Wil",
	"Yara",
	"Zia",
	"Wren",
	"Moss",
	"Dune",
	"Sunna",
	"Lior",
	"Yael",
	"Ivo",
	"Reed",
	"Arlo",
	"Hugo",
	"Mace",
	"Rory",
	"Otter",
	"Ozzie",
	"Elm",
	"Tove",
	"Maren",
	"Zora",
	"June",
	"Sol",
	"Britt",
	"Basil",
	"Pell",
	"Flint",
	"Ansel",
	"Noor",
	"Abel",
	"Juniper",
	"Rune",
	"Gale",
	"Birdie",
	"Oda",
	"Bo",
	"Koa",
	"Tam",
	"Cy",
	"Isla",
	"Nico",
	"Sia",
	"Cobalt",
	"Sorrel",
	"Hollis",
	"Corin",
	"Pim",
	"Fig",
	"Thane",
	"Iris",
	"Delphi",
	"Ren",
	"Cass",
	"Lin",
	"Ulf",
	"Dara",
	"Jett",
	"Opal",
	"Tess",
	"Marlowe",
	"Ulla",
	"Jory",
	"Edda",
	"Saga",
	"Dov",
	"Milo",
	"Vale",
	"Pico",
	"Vesper",
	"Kit",
	"Faro",
	"Sable",
	"Wick",
	"Lyle",
	"Greer",
	"Teo",
	"Esme",
	"Nia",
	"Wes",
	"Eli",
	"Kip",
	"Ida",
	"Yarrow",
	"Mira",
	"Hale",
	"Uma",
	"Finch",
	"Oren",
	"Yuki",
	"Fenn",
	"Zed",
	"Nell",
	"Inga",
	"Vida",
	"Gus",
	"Quill",
	"Ash",
	"Orrin",
	"Jules",
	"Wynn",
	"Tamsin",
	"Bram",
	"Petra",
	"Ember",
	"Alder",
	"Aspen",
	"Bay",
	"Brook",
	"Bower",
	"Cinder",
	"Cliff",
	"Clover",
	"Cairn",
	"Cove",
	"Dale",
	"Dora",
	"Dusk",
	"Doe",
	"Ebb",
	"Echo",
	"Fern",
	"Field",
	"Firth",
	"Glen",
	"Garnet",
	"Harbor",
	"Hazel",
	"Heath",
	"Hana",
	"Hurst",
	"Inlet",
	"Ivy",
	"Jonas",
	"Kara",
	"Kelp",
	"Knoll",
	"Liv",
	"Lumen",
	"Loam",
	"Maple",
	"Meadow",
	"Mere",
	"Mica",
	"Mist",
	"Nadia",
	"Nettle",
	"Onyx",
	"Orchard",
	"Ozone",
	"Palm",
	"Patch",
	"Pebble",
	"Pine",
	"Plume",
	"Pond",
	"Quarry",
	"Rain",
	"Ridge",
	"River",
	"Rill",
	"Rosa",
	"Rowan",
	"Sedge",
	"Shale",
	"Shore",
	"Silas",
	"Skye",
	"Slate",
	"Spruce",
	"Stone",
	"Stream",
	"Tarn",
	"Tide",
	"Timber",
	"Tomas",
	"Topaz",
	"Wadi",
	"Wold",
	"Yew",
	"Zephyr",
	"Ada",
	"Amos",
	"Elsa",
	"Erik",
	"Grove",
	"Tern",
	"Afton",
];

// The dataset pairs that share a three-letter prefix, kept verbatim.
export const KNOWN_PREFIX_PAIRS: readonly (readonly [string, string])[] = [
	["Yara", "Yarrow"],
	["Maren", "Marlowe"],
	["June", "Juniper"],
	["Tam", "Tamsin"],
];

// Deterministic pick from `seed`, skipping `taken`. Linear probe from the
// hashed seed, so the same seed always yields the same free name.
export function pickName(taken: Set<string>, seed: string): string {
	if (taken.size >= NAME_POOL.length) {
		throw new Error("agent name pool exhausted");
	}
	const digest = createHash("sha256").update(seed).digest();
	const index = digest.readUInt32BE(0) % NAME_POOL.length;
	for (let i = 0; i < NAME_POOL.length; i++) {
		const name = NAME_POOL[(index + i) % NAME_POOL.length];
		if (!taken.has(name)) {
			return name;
		}
	}
	throw new Error("agent name pool exhausted");
}
